# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:

  build:
    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout
      - run: 
          name: build
          command: |
            $ProgressPreference = "SilentlyContinue"
            
            msbuild "DeveloperCore\DeveloperCore.vbproj" /p:Configuration=Release /t:restore,build /p:RestorePackagesConfig=true
workflows:
  version: 2
  build_and_upload_artifact:
    jobs:
      - build